language: php

php:
    - 5.4
    - 5.5

before_script:
    - mysql -e 'create database couchdb;'
    - cat src/schema/*.sql | mysql couchdb

install: ant -logger org.apache.tools.ant.NoBannerLogger initialize

script: ant -logger org.apache.tools.ant.NoBannerLogger test

cache:
    directories:
        - vendor
