; Properties determining, if the build should fail, if one of the tests fails
test-unit.fail-on-violation = true
test-feature.fail-on-violation = true
test-static-cpd.fail-on-violation = true
test-static-checkstyle.fail-on-violation = true
test-static-pmd.fail-on-violation = true
test-static-pdepend.fail-on-violation = false

coding.standard=PSR2
